/// Unit tests for the on-chain STARK verifier primitives.
///
/// Covers Phase A.1 (Goldilocks field arithmetic) and Phase A.2 (Merkle
/// verify). Known-good vectors were generated by the Python prover
/// (`zkp/core/cuda_true_stark.py`); any drift here indicates the Move
/// port has diverged from what the prover emits.
#[test_only]
#[allow(unused_use, unused_const)]
module zkvanguard::zkv_stark_tests {
    use zkvanguard::zkv_field;
    use zkvanguard::zkv_merkle::{Self, MerkleProofStep};
    use zkvanguard::zkv_fri;

    // ============ Field constants ============
    // p = 2^64 - 2^32 + 1 = 18446744069414584321
    const P: u64 = 18446744069414584321;
    const P_MINUS_1: u64 = 18446744069414584320;
    const P_MINUS_2: u64 = 18446744069414584319;

    // ============ Field: prime + identity ============

    #[test]
    fun prime_matches_config() {
        assert!(zkv_field::prime() == P, 0);
    }

    #[test]
    fun add_zero_is_identity() {
        assert!(zkv_field::add(0, 42) == 42, 0);
        assert!(zkv_field::add(42, 0) == 42, 0);
    }

    #[test]
    fun add_wraps_at_prime() {
        // (P - 1) + 1 = 0
        assert!(zkv_field::add(P_MINUS_1, 1) == 0, 0);
        // (P - 1) + 2 = 1
        assert!(zkv_field::add(P_MINUS_1, 2) == 1, 0);
    }

    #[test]
    fun add_handles_max_u64_operands() {
        // Both operands near P; sum overflows u64 but must reduce cleanly.
        // (P - 5) + (P - 5) = 2P - 10 ≡ -10 ≡ P - 10 (mod P).
        let expected = P - 10;
        assert!(zkv_field::add(P_MINUS_1 - 4, P_MINUS_1 - 4) == expected, 0);
    }

    // ============ Field: subtraction ============

    #[test]
    fun sub_basic() {
        assert!(zkv_field::sub(10, 3) == 7, 0);
        assert!(zkv_field::sub(5, 5) == 0, 0);
    }

    #[test]
    fun sub_underflow_wraps_to_prime() {
        // 3 - 10 ≡ P - 7 (mod P)
        assert!(zkv_field::sub(3, 10) == P - 7, 0);
    }

    // ============ Field: multiplication ============

    #[test]
    fun mul_basic() {
        assert!(zkv_field::mul(6, 7) == 42, 0);
        assert!(zkv_field::mul(0, 999) == 0, 0);
        assert!(zkv_field::mul(1, 999) == 999, 0);
    }

    #[test]
    fun mul_handles_full_range() {
        // (P-1) * (P-1) mod P = 1  (since (-1)*(-1) = 1)
        assert!(zkv_field::mul(P_MINUS_1, P_MINUS_1) == 1, 0);
    }

    // ============ Field: negation ============

    #[test]
    fun neg_zero_is_zero() {
        assert!(zkv_field::neg(0) == 0, 0);
    }

    #[test]
    fun neg_and_add_cancels() {
        let a: u64 = 12345;
        assert!(zkv_field::add(a, zkv_field::neg(a)) == 0, 0);
    }

    // ============ Field: pow ============

    #[test]
    fun pow_zero_is_one() {
        assert!(zkv_field::pow(7, 0) == 1, 0);
    }

    #[test]
    fun pow_one_is_base() {
        assert!(zkv_field::pow(7, 1) == 7, 0);
    }

    #[test]
    fun pow_matches_hand_computation() {
        // 3^5 = 243
        assert!(zkv_field::pow(3, 5) == 243, 0);
        // 2^10 = 1024
        assert!(zkv_field::pow(2, 10) == 1024, 0);
    }

    #[test]
    fun pow_p_minus_1_is_one() {
        // Fermat: a^(p-1) = 1 for a != 0.
        assert!(zkv_field::pow(7, P_MINUS_1) == 1, 0);
        assert!(zkv_field::pow(12345, P_MINUS_1) == 1, 0);
    }

    // ============ Field: inv + div ============

    #[test]
    fun inv_then_mul_yields_one() {
        let a: u64 = 7;
        assert!(zkv_field::mul(a, zkv_field::inv(a)) == 1, 0);
        let b: u64 = 99999;
        assert!(zkv_field::mul(b, zkv_field::inv(b)) == 1, 0);
    }

    #[test]
    #[expected_failure(abort_code = 0)]
    fun inv_zero_aborts() {
        zkv_field::inv(0);
    }

    #[test]
    fun div_matches_mul_inv() {
        // 42 / 6 in the field == 42 * inv(6) == 7
        assert!(zkv_field::div(42, 6) == 7, 0);
    }

    #[test]
    fun eq_reduces_before_comparing() {
        // Values above P should still compare equal after reduction.
        // 0 and P both reduce to 0.
        assert!(zkv_field::eq(0, 0), 0);
    }

    // ============ Merkle verify — known-good vector ============
    //
    // Tree built via zkp/core/cuda_true_stark.py::MerkleTree(leaves=[
    //     b'leaf_a', b'leaf_b', b'leaf_c', b'leaf_d'
    // ]), proving inclusion of leaf_c (index=2). Vectors generated by
    // reproducible Python computation on 2026-07-28.

    fun leaf_c(): vector<u8> {
        // b'leaf_c' as raw bytes
        x"6c6561665f63"
    }

    fun bad_leaf(): vector<u8> {
        // b'leaf_x'
        x"6c6561665f78"
    }

    fun proof_for_leaf_c(): vector<MerkleProofStep> {
        vector[
            zkv_merkle::new_step(
                x"65a71ead52358266086a3f6b7cdadf1b6b66e95cc6df4d78db9a3d1348f28f7d",
                true,  // current(leaf_c-hash) sits on LEFT at level 0
            ),
            zkv_merkle::new_step(
                x"02bd8542459161387133827baecfb4aaa45e604059678a4e9e720d7cdadb1eda",
                false, // current(l1[1]) sits on RIGHT at level 1
            ),
        ]
    }

    fun good_root(): vector<u8> {
        x"e3b58dfe27716ef42537b185903ddb93571f28061805339c06ab5d19cc87baa2"
    }

    fun wrong_root(): vector<u8> {
        x"0000000000000000000000000000000000000000000000000000000000000000"
    }

    #[test]
    fun merkle_verify_good_leaf_good_proof_good_root() {
        assert!(zkv_merkle::verify(leaf_c(), proof_for_leaf_c(), good_root()), 0);
    }

    #[test]
    fun merkle_verify_bad_leaf_rejected() {
        // Same proof, wrong leaf → rejects.
        assert!(!zkv_merkle::verify(bad_leaf(), proof_for_leaf_c(), good_root()), 0);
    }

    #[test]
    fun merkle_verify_wrong_root_rejected() {
        assert!(!zkv_merkle::verify(leaf_c(), proof_for_leaf_c(), wrong_root()), 0);
    }

    #[test]
    fun merkle_verify_tampered_sibling_rejected() {
        // Flip a byte in the level-0 sibling — should not recompute to root.
        let bad_proof = vector[
            zkv_merkle::new_step(
                x"00a71ead52358266086a3f6b7cdadf1b6b66e95cc6df4d78db9a3d1348f28f7d",
                true,
            ),
            zkv_merkle::new_step(
                x"02bd8542459161387133827baecfb4aaa45e604059678a4e9e720d7cdadb1eda",
                false,
            ),
        ];
        assert!(!zkv_merkle::verify(leaf_c(), bad_proof, good_root()), 0);
    }

    #[test]
    fun merkle_verify_flipped_side_rejected() {
        // Correct sibling hashes but wrong is_left flag → rejects.
        let bad_proof = vector[
            zkv_merkle::new_step(
                x"65a71ead52358266086a3f6b7cdadf1b6b66e95cc6df4d78db9a3d1348f28f7d",
                false,  // wrong (was true)
            ),
            zkv_merkle::new_step(
                x"02bd8542459161387133827baecfb4aaa45e604059678a4e9e720d7cdadb1eda",
                false,
            ),
        ];
        assert!(!zkv_merkle::verify(leaf_c(), bad_proof, good_root()), 0);
    }

    #[test]
    fun merkle_verify_empty_proof_accepts_only_when_leaf_hash_is_root() {
        use std::hash;
        // An empty proof means "the leaf is the root" — should accept iff
        // sha256(leaf) == root. Single-leaf tree case.
        let leaf = b"solo";
        let root = hash::sha2_256(leaf);
        assert!(zkv_merkle::verify(leaf, vector[], root), 0);
        // Any other root must reject.
        assert!(!zkv_merkle::verify(leaf, vector[], wrong_root()), 0);
    }

    // ============ Field helpers: u64_to_ascii + eval_poly + primitive_root ============

    #[test]
    fun u64_to_ascii_zero() {
        assert!(zkv_field::u64_to_ascii(0) == b"0", 0);
    }

    #[test]
    fun u64_to_ascii_single_digit() {
        assert!(zkv_field::u64_to_ascii(7) == b"7", 0);
    }

    #[test]
    fun u64_to_ascii_multi_digit() {
        assert!(zkv_field::u64_to_ascii(42) == b"42", 0);
        assert!(zkv_field::u64_to_ascii(12345) == b"12345", 0);
    }

    #[test]
    fun u64_to_ascii_max_u64() {
        // 18446744073709551615 = 2^64 - 1
        assert!(zkv_field::u64_to_ascii(18446744073709551615) == b"18446744073709551615", 0);
    }

    #[test]
    fun eval_poly_empty_is_zero() {
        assert!(zkv_field::eval_poly(&vector[], 42) == 0, 0);
    }

    #[test]
    fun eval_poly_constant() {
        // P(x) = 7 for any x
        assert!(zkv_field::eval_poly(&vector[7], 999) == 7, 0);
    }

    #[test]
    fun eval_poly_linear() {
        // P(x) = 3 + 5x, evaluated at 4: = 3 + 20 = 23
        assert!(zkv_field::eval_poly(&vector[3, 5], 4) == 23, 0);
    }

    #[test]
    fun eval_poly_quadratic() {
        // P(x) = 1 + 2x + 3x², at x=10: = 1 + 20 + 300 = 321
        assert!(zkv_field::eval_poly(&vector[1, 2, 3], 10) == 321, 0);
    }

    #[test]
    fun primitive_root_of_order_2_squares_to_one() {
        // The only order-2 root of unity is -1 (P - 1).
        let r = zkv_field::primitive_root(2);
        assert!(zkv_field::mul(r, r) == 1, 0);
        assert!(r == P_MINUS_1, 0);
    }

    #[test]
    fun primitive_root_of_order_4_has_order_4() {
        let r = zkv_field::primitive_root(4);
        // r^4 = 1 but r^2 != 1.
        assert!(zkv_field::pow(r, 4) == 1, 0);
        assert!(zkv_field::pow(r, 2) != 1, 0);
    }

    // ============ FRI: coset_shift_for + challenge_from_root ============

    #[test]
    fun coset_shift_matches_primitive_root_of_2N() {
        // Prover uses get_primitive_root(extended_size * 2) as the coset
        // shift; verifier must derive it the same way.
        let extended_size: u64 = 256;
        assert!(zkv_fri::coset_shift_for(extended_size)
                == zkv_field::primitive_root(extended_size * 2), 0);
    }

    #[test]
    fun coset_shift_is_outside_subgroup() {
        // h^N = -1 (i.e., h is a primitive 2N-th root, so h^N has order 2).
        let extended_size: u64 = 256;
        let h = zkv_fri::coset_shift_for(extended_size);
        let h_pow_n = zkv_field::pow(h, extended_size);
        assert!(h_pow_n == P_MINUS_1, 0);
    }

    #[test]
    fun challenge_from_zero_root_matches_python() {
        // Golden vector from Python:
        //   sha256(b'\0' * 32) = 66687aad...
        //   int(digest, 16) % P = 7657728858192895983
        let root: vector<u8> = x"0000000000000000000000000000000000000000000000000000000000000000";
        assert!(zkv_fri::challenge_from_root(&root) == 7657728858192895983, 0);
    }

    #[test]
    fun challenge_from_nontrivial_root_matches_python() {
        // Golden vector: root = b"zkvanguard_test_root_00000000000\x01"
        let root: vector<u8> = x"7a6b76616e67756172645f746573745f726f6f745f3030303030303030303001";
        assert!(zkv_fri::challenge_from_root(&root) == 11069442325780867913, 0);
    }

    // ============ FRI: negative / structural cases ============

    #[test]
    fun fri_verify_empty_roots_rejects() {
        // No layer roots → not a valid proof.
        assert!(!zkv_fri::verify(
            vector[],
            vector[],
            vector[],
            1024,
            80,
        ), 0);
    }

    #[test]
    fun fri_verify_oversized_final_poly_rejects() {
        // Final polynomial coefficient count > max_final_degree + 1 → reject.
        // Even with a single (trivially-invalid) root, degree check fires first.
        let roots = vector[x"0000000000000000000000000000000000000000000000000000000000000000"];
        let too_many_coeffs = vector[
            1u64, 2u64, 3u64, 4u64, 5u64, 6u64, 7u64, 8u64, 9u64, 10u64,
            11u64, 12u64, 13u64, 14u64, 15u64, 16u64, 17u64, 18u64, 19u64, 20u64,
        ];
        assert!(!zkv_fri::verify(
            roots,
            vector[],
            too_many_coeffs,
            1024,
            8,  // max degree 8 → 9 coeffs max, but we supply 20
        ), 0);
    }

    #[test]
    fun fri_verify_underlength_query_rejects() {
        // Query with fewer layers than the number of layer roots must reject
        // (would otherwise index past the end).
        let roots = vector[
            x"0000000000000000000000000000000000000000000000000000000000000000",
            x"1111111111111111111111111111111111111111111111111111111111111111",
        ];
        let query = zkv_fri::new_query(0, vector[]);  // 0 layers < 2 roots
        assert!(!zkv_fri::verify(
            roots,
            vector[query],
            vector[0u64],
            256,
            8,
        ), 0);
    }
}
