/// Unit tests for the on-chain STARK verifier primitives.
///
/// Covers Phase A.1 (Goldilocks field arithmetic) and Phase A.2 (Merkle
/// verify). Known-good vectors were generated by the Python prover
/// (`zkp/core/cuda_true_stark.py`); any drift here indicates the Move
/// port has diverged from what the prover emits.
#[test_only]
#[allow(unused_use, unused_const)]
module zkvanguard::zkv_stark_tests {
    use zkvanguard::zkv_field;
    use zkvanguard::zkv_merkle::{Self, MerkleProofStep};

    // ============ Field constants ============
    // p = 2^64 - 2^32 + 1 = 18446744069414584321
    const P: u64 = 18446744069414584321;
    const P_MINUS_1: u64 = 18446744069414584320;
    const P_MINUS_2: u64 = 18446744069414584319;

    // ============ Field: prime + identity ============

    #[test]
    fun prime_matches_config() {
        assert!(zkv_field::prime() == P, 0);
    }

    #[test]
    fun add_zero_is_identity() {
        assert!(zkv_field::add(0, 42) == 42, 0);
        assert!(zkv_field::add(42, 0) == 42, 0);
    }

    #[test]
    fun add_wraps_at_prime() {
        // (P - 1) + 1 = 0
        assert!(zkv_field::add(P_MINUS_1, 1) == 0, 0);
        // (P - 1) + 2 = 1
        assert!(zkv_field::add(P_MINUS_1, 2) == 1, 0);
    }

    #[test]
    fun add_handles_max_u64_operands() {
        // Both operands near P; sum overflows u64 but must reduce cleanly.
        // (P - 5) + (P - 5) = 2P - 10 ≡ -10 ≡ P - 10 (mod P).
        let expected = P - 10;
        assert!(zkv_field::add(P_MINUS_1 - 4, P_MINUS_1 - 4) == expected, 0);
    }

    // ============ Field: subtraction ============

    #[test]
    fun sub_basic() {
        assert!(zkv_field::sub(10, 3) == 7, 0);
        assert!(zkv_field::sub(5, 5) == 0, 0);
    }

    #[test]
    fun sub_underflow_wraps_to_prime() {
        // 3 - 10 ≡ P - 7 (mod P)
        assert!(zkv_field::sub(3, 10) == P - 7, 0);
    }

    // ============ Field: multiplication ============

    #[test]
    fun mul_basic() {
        assert!(zkv_field::mul(6, 7) == 42, 0);
        assert!(zkv_field::mul(0, 999) == 0, 0);
        assert!(zkv_field::mul(1, 999) == 999, 0);
    }

    #[test]
    fun mul_handles_full_range() {
        // (P-1) * (P-1) mod P = 1  (since (-1)*(-1) = 1)
        assert!(zkv_field::mul(P_MINUS_1, P_MINUS_1) == 1, 0);
    }

    // ============ Field: negation ============

    #[test]
    fun neg_zero_is_zero() {
        assert!(zkv_field::neg(0) == 0, 0);
    }

    #[test]
    fun neg_and_add_cancels() {
        let a: u64 = 12345;
        assert!(zkv_field::add(a, zkv_field::neg(a)) == 0, 0);
    }

    // ============ Field: pow ============

    #[test]
    fun pow_zero_is_one() {
        assert!(zkv_field::pow(7, 0) == 1, 0);
    }

    #[test]
    fun pow_one_is_base() {
        assert!(zkv_field::pow(7, 1) == 7, 0);
    }

    #[test]
    fun pow_matches_hand_computation() {
        // 3^5 = 243
        assert!(zkv_field::pow(3, 5) == 243, 0);
        // 2^10 = 1024
        assert!(zkv_field::pow(2, 10) == 1024, 0);
    }

    #[test]
    fun pow_p_minus_1_is_one() {
        // Fermat: a^(p-1) = 1 for a != 0.
        assert!(zkv_field::pow(7, P_MINUS_1) == 1, 0);
        assert!(zkv_field::pow(12345, P_MINUS_1) == 1, 0);
    }

    // ============ Field: inv + div ============

    #[test]
    fun inv_then_mul_yields_one() {
        let a: u64 = 7;
        assert!(zkv_field::mul(a, zkv_field::inv(a)) == 1, 0);
        let b: u64 = 99999;
        assert!(zkv_field::mul(b, zkv_field::inv(b)) == 1, 0);
    }

    #[test]
    #[expected_failure(abort_code = 0)]
    fun inv_zero_aborts() {
        zkv_field::inv(0);
    }

    #[test]
    fun div_matches_mul_inv() {
        // 42 / 6 in the field == 42 * inv(6) == 7
        assert!(zkv_field::div(42, 6) == 7, 0);
    }

    #[test]
    fun eq_reduces_before_comparing() {
        // Values above P should still compare equal after reduction.
        // 0 and P both reduce to 0.
        assert!(zkv_field::eq(0, 0), 0);
    }

    // ============ Merkle verify — known-good vector ============
    //
    // Tree built via zkp/core/cuda_true_stark.py::MerkleTree(leaves=[
    //     b'leaf_a', b'leaf_b', b'leaf_c', b'leaf_d'
    // ]), proving inclusion of leaf_c (index=2). Vectors generated by
    // reproducible Python computation on 2026-07-28.

    fun leaf_c(): vector<u8> {
        // b'leaf_c' as raw bytes
        x"6c6561665f63"
    }

    fun bad_leaf(): vector<u8> {
        // b'leaf_x'
        x"6c6561665f78"
    }

    fun proof_for_leaf_c(): vector<MerkleProofStep> {
        vector[
            zkv_merkle::new_step(
                x"65a71ead52358266086a3f6b7cdadf1b6b66e95cc6df4d78db9a3d1348f28f7d",
                true,  // current(leaf_c-hash) sits on LEFT at level 0
            ),
            zkv_merkle::new_step(
                x"02bd8542459161387133827baecfb4aaa45e604059678a4e9e720d7cdadb1eda",
                false, // current(l1[1]) sits on RIGHT at level 1
            ),
        ]
    }

    fun good_root(): vector<u8> {
        x"e3b58dfe27716ef42537b185903ddb93571f28061805339c06ab5d19cc87baa2"
    }

    fun wrong_root(): vector<u8> {
        x"0000000000000000000000000000000000000000000000000000000000000000"
    }

    #[test]
    fun merkle_verify_good_leaf_good_proof_good_root() {
        assert!(zkv_merkle::verify(leaf_c(), proof_for_leaf_c(), good_root()), 0);
    }

    #[test]
    fun merkle_verify_bad_leaf_rejected() {
        // Same proof, wrong leaf → rejects.
        assert!(!zkv_merkle::verify(bad_leaf(), proof_for_leaf_c(), good_root()), 0);
    }

    #[test]
    fun merkle_verify_wrong_root_rejected() {
        assert!(!zkv_merkle::verify(leaf_c(), proof_for_leaf_c(), wrong_root()), 0);
    }

    #[test]
    fun merkle_verify_tampered_sibling_rejected() {
        // Flip a byte in the level-0 sibling — should not recompute to root.
        let bad_proof = vector[
            zkv_merkle::new_step(
                x"00a71ead52358266086a3f6b7cdadf1b6b66e95cc6df4d78db9a3d1348f28f7d",
                true,
            ),
            zkv_merkle::new_step(
                x"02bd8542459161387133827baecfb4aaa45e604059678a4e9e720d7cdadb1eda",
                false,
            ),
        ];
        assert!(!zkv_merkle::verify(leaf_c(), bad_proof, good_root()), 0);
    }

    #[test]
    fun merkle_verify_flipped_side_rejected() {
        // Correct sibling hashes but wrong is_left flag → rejects.
        let bad_proof = vector[
            zkv_merkle::new_step(
                x"65a71ead52358266086a3f6b7cdadf1b6b66e95cc6df4d78db9a3d1348f28f7d",
                false,  // wrong (was true)
            ),
            zkv_merkle::new_step(
                x"02bd8542459161387133827baecfb4aaa45e604059678a4e9e720d7cdadb1eda",
                false,
            ),
        ];
        assert!(!zkv_merkle::verify(leaf_c(), bad_proof, good_root()), 0);
    }

    #[test]
    fun merkle_verify_empty_proof_accepts_only_when_leaf_hash_is_root() {
        use std::hash;
        // An empty proof means "the leaf is the root" — should accept iff
        // sha256(leaf) == root. Single-leaf tree case.
        let leaf = b"solo";
        let root = hash::sha2_256(leaf);
        assert!(zkv_merkle::verify(leaf, vector[], root), 0);
        // Any other root must reject.
        assert!(!zkv_merkle::verify(leaf, vector[], wrong_root()), 0);
    }
}
