export const presets = {
  conservative: {
    targetYield: 500,
    riskTolerance: 25,
    maxDrawdown: 10,
    concentrationLimit: 20,
    hedgingEnabled: true,
    rebalanceFrequency: 'weekly' as const,
    autoApprovalEnabled: true,
    autoApprovalThreshold: 5000,
  },
  balanced: {
    targetYield: 1000,
    riskTolerance: 50,
    maxDrawdown: 20,
    concentrationLimit: 30,
    hedgingEnabled: true,
    rebalanceFrequency: 'weekly' as const,
    autoApprovalEnabled: true,
    autoApprovalThreshold: 10000,
  },
  aggressive: {
    targetYield: 2000,
    riskTolerance: 80,
    maxDrawdown: 35,
    concentrationLimit: 50,
    hedgingEnabled: true,
    rebalanceFrequency: 'daily' as const,
    autoApprovalEnabled: true,
    autoApprovalThreshold: 25000,
  },
};
